name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file GayDetectorBot.Telegram/Dockerfile --tag gaydetectorbot:$(date +%s)
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./GayDetectorBot.Telegram/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gay_detector_bot:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

